/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Category = IDL.Variant({
  'dessert' : IDL.Null,
  'seafood' : IDL.Null,
  'meat' : IDL.Null,
  'highlights' : IDL.Null,
  'specialty' : IDL.Null,
  'vegetarian' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageURL' : IDL.Text,
  'category' : Category,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'findMenuItem' : IDL.Func([IDL.Text], [IDL.Opt(MenuItem)], ['query']),
  'getItemsByCategory' : IDL.Func([Category], [IDL.Vec(MenuItem)], ['query']),
  'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getRestaurantInfo' : IDL.Func([], [IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Category = IDL.Variant({
    'dessert' : IDL.Null,
    'seafood' : IDL.Null,
    'meat' : IDL.Null,
    'highlights' : IDL.Null,
    'specialty' : IDL.Null,
    'vegetarian' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageURL' : IDL.Text,
    'category' : Category,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'findMenuItem' : IDL.Func([IDL.Text], [IDL.Opt(MenuItem)], ['query']),
    'getItemsByCategory' : IDL.Func([Category], [IDL.Vec(MenuItem)], ['query']),
    'getMenu' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getRestaurantInfo' : IDL.Func([], [IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };